[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[start]
cmd = "node dist/index.js"
